### ISSUE TITLE
'subused subuser add' broken in http://subuser.org/packaging.html

### ISSUE THREAD

**Issue by danmbox** [subuser-security/subuser#189]
`subuser subuser add my-new-subuser my-new-subuser@file:///home/timothy/my-subuser-programs/` should instead be `subuser subuser add my-new-subuser my-subuser-image@file:///home/timothy/my-subuser-programs/` (but really, the tutorial steps should be fully tested at least once...)

**Comment by timthelion** [comment]
Thank you for your feedback. You are right, I should have been more careful. I really thought to myself "this is so simple, I cannot possibly make a mistake" of course, famous last words, right ;). Now I have gone  through the tutorial and tested it myself, and I even found one more typo...

I hope you didn't lose too much time due to my errors.

Tim
