### ISSUE TITLE
Hjson Configuration

### ISSUE THREAD

**Issue by laktak** [subuser-security/subuser#192]
Well your contribution guidelines say no external dependencies but having your configuration files in JSON is not optimal.

If you ever change your policy take a look at [Hjson](http://hjson.org) - it's a configuration file format that caters to humans and helps reduce the errors they make.

**Comment by peter1000** [comment]
@laktak I just skipped over your hjson.  Just out of interest: what is the speed comparison to pythons included c json?

**Comment by laktak** [comment]
I haven't done any speed tests before as config tend to be small and not parsed very often.

It's an interesting question though, so:

```
{
 "description"                : "The firefox web browser.\nNote: If you have a different version of firefox running already, you must launch firefox with the -new-instance command line argument."
 ,"maintainer"                : "Timothy Hobbs <timothyhobbs (at) seznam dot cz>"
 ,"last-update-time"          : "2014-02-12-12:59"
 ,"executable"                : "/usr/bin/firefox"
 ,"user-dirs"                 : ["Downloads"]
 ,"x11"                       : true
 ,"sound-card"                     : true
 ,"allow-network-access"      : true
 ,"basic-common-permissions" : true
}
```
vs.
```
{
  description:
    '''
    The firefox web browser.
    Note: If you have a different version of firefox running already, you must launch firefox with the -new-instance command line argument.
    '''
  maintainer: Timothy Hobbs <timothyhobbs (at) seznam dot cz>
  last-update-time: 2014-02-12-12:59
  executable: /usr/bin/firefox
  user-dirs:
  [
    Downloads
  ]
  x11: true
  sound-card: true
  allow-network-access: true
  basic-common-permissions: true
}
```

JSON parses it in .011 ms per iteration while Hjson needs 0.267 ms (*on my machine*).

**Comment by timthelion** [comment]
I wonder if the universal data serialization format war will ever resolve itself.  Maybe there will just be more and more serialization formats, just as there are more and more programming languages. Has anyone created an esoteric data serialization format yet? What is the brainfuck of serialization formats? XML? ;)

I think that one of the things hindering the creation of an essoteric serialization format is the lack of some standard definition of the "turing completeness" of a data structure. For example, JSON is good enough to be able to record any kind of data (You can always just stuff more complex structures into a string) but it is not able to record the STRUCTURE of any kind of data. You cannot describe the structure of a [graph](https://en.wikipedia.org/wiki/Graph_%28mathematics%29) using JSON! I guess our lack of the ability to say when a data structure description language is universal really goes to show how primitive our understanding of data structure is when compaired to our understanding of computation.

I'm sorry for the long and irrelevant thought!

I personally, would like JSON to allow for comments in a future version.

I think that:

````
  user-dirs:
  [
    Downloads
  ]
````

might look a bit better if there WERE quotes around the folder names, but if I understand correctly, with hjson, those could just be added in, right?

In the end, though, I have written the subuser standard as a standard so that multiple PROGRAMs could read and write the serialized data, rather than that humans could do so. For example, I would much rather that there was a GUI program that helped users edit their permissions files, rather than having them edit the JSON manually, than to change the JSON to some better textual format. And for multiple programs to edit the serialized data, JSON is currently the best choice, because it is currently the most widely supported serialization format in the world.

That said, I too want to comment my JSON!

Tim

**Comment by laktak** [comment]
Yes you can write `user-dirs: [ "Downloads" ]`.

JSON will not allow comments as there won't be a v2. JSON is also not the right tool for a configuration file. That wasn't the goal.

I don't agree with your opinion (GUI) but if you are fine with JSON that's OK. Just wanted to let you know there are other options.
