### ISSUE TITLE
Non x86-64 architectures are not well supported

### ISSUE THREAD

**Issue by Happy-Ferret** [subuser-security/subuser#253]
Running the following command fails to build the image, leaving that subuser id in a broken state. 

```
subuser subuser add vim1 vim@default
```

Error message:

```
 ---> Running in 6d186b838511

Removing intermediate container 6d186b838511

Build error:exec format error


Images for the following subusers failed to build:
vim1
Running garbage collector on temporary repositories...
[master f1edf91] Adding subuser vim1 vim@default Verifying subuser configuration. Verifying registry consistency... Unregistering any non-existant installed images. Checking if images need to be updated or installed... Checking if subuser vim1 is up to date. Installing libdebian ... Step 0 : FROM debian
 7 files changed, 84 insertions(+), 1 deletion(-)
 create mode 100644 permissions/!service-subuser-firefox1-xpra-client/permissions.json
 create mode 100644 permissions/!service-subuser-firefox1-xpra-server/permissions.json
 create mode 100644 permissions/firefox1/permissions-template.json
 create mode 100644 permissions/firefox1/permissions.json
 create mode 100644 permissions/vim1/permissions-template.json
 create mode 100644 permissions/vim1/permissions.json
```

I used the alias "vim1" because the build already failed once and I still have to figure out what files I need to remove in order to properly get rid of the image again.

System: 

```
Ubuntu 15.04 (3.19 kernel@stock) i686
Python 2.7.9
Docker 1.5
```

Subuser was installed through pip.

**Comment by timthelion** [comment]
The problem is that subuser is using the default images from the Docker hub, and these images do not support 32 bit systems (you write that you are on i686).
 https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1366509

It may be possible to create subuser repositories for non x86-64 architectures, I haven't tried it yet. But it is not a priority for me.

I'm sorry that the error message is not more user friendly. It should tell you the problem clearly and imediately. However, that would be a bug to file against ubuntu's version of Docker and not a bug in subuser.

Have a nice day,

Timothy Hobbs

**Comment by Happy-Ferret** [comment]
Thanks. That's good to know. 

Not a problem at all either. I normally run x86_64 OS' anyways. Was just a quick spin-up and that 32 bit Ubuntu ISO happened to sit around on my HDD. 

I'll report back once I've set up a proper 64 bit distro.

**Comment by timthelion** [comment]
These are dups https://github.com/subuser-security/subuser/issues/274
