### ISSUE TITLE
pkg command not found

### ISSUE THREAD

**Issue by Fiedzia** [subuser-security/subuser#258]
I'm trying to follow tutorial (http://subuser.org/packaging.html)

I did:

sudo pip3 install subuser
 subuser pkg init
> Command not found: pkg

It seems that pypi should be updated.

**Comment by timthelion** [comment]
Yes, pypi should definitely be updated. I've been in the process of some major bug-fixes and, since the previous releases have not been of stellar quality, I want the next one to be. However, my desire for quality in the next release has only lead to the next release being put off further and further, thus causing people to use the poor quality code for longer. A bit of a paradox, I know.

**Comment by Fiedzia** [comment]
|I suggest to release regularly. Make improving quality a process, not a one-time effort,
this will make it easier for others to help you.

**Comment by timthelion** [comment]
I will try to get a new release out as quickly as possible.

**Comment by timthelion** [comment]
I have recently released a 0.5 release which should have all of the features that you needed :)
