### ISSUE TITLE
Question: How to handle dotfiles

### ISSUE THREAD

**Issue by duerrp** [subuser-security/subuser#285]
Thanks for your efforts, subuser looks very interesting! 

How do you propose to handle dotfiles that should go to the subuser's home directory? Copy them there by script after installing the subuser?

**Comment by timthelion** [comment]
Normally on POSIX programs create dot files on startup. This can be done with subuser using a wrapper script https://github.com/subuser-security/subuser-examples/tree/master/vim-with-dotfile-autocreation . This has a very slight performance penalty due to the need to load bash before whatever you want to run. Is that performance pentalty a problem for you?

**Comment by duerrp** [comment]
@timthelion 
Thanks for the quick reply. I understand your method and I don't think the performance hit is a problem for me. For elegance points, it would be nice to have a hook to run scripts after installing a new subuser (or supply default home-dir contents), but I guess it's not crucial.

**Comment by timthelion** [comment]
The trouble with supplying default home dir contents (and yes, it has
been discussed extensively in the Debian project) is that there is no
good way of merging the new configs with the old, potentialy user
modified ones. That is the reason why it is prefered to re-create
configs if they are deleted. It allows the user to choose to upgrade
their config files/return to a clean slate simply by deleting them.
