### ISSUE TITLE
Shared dependencies

### ISSUE THREAD

**Issue by SuicSoft** [subuser-security/subuser#289]
Subuser does not share dependencies between packages.It should do this to save space and reduce download time

**Comment by timthelion** [comment]
This is the bigest frustration for me with subuser. As I've stated elsewhere, I keep hoping for an actual de-duplicating file system a-la [IPFS](ipfs.io) to serve as a backend to subuser. That would solve this problem.

However, working within the contstraints of Docker's layer system I think there is still some room for improvement. Right now, most images are built from the `libx11` layer. https://github.com/subuser-security/subuser-default-repository/tree/latest/libx11
I've been considering renaming that layer `libeverything` and just packing that image with every dependency imaginable. Its not a great solution, and it still means that everything gets re-installed when you update the system :(. But it would probably be better than the current system.

**Comment by timthelion** [comment]
So I've crammed everything together into one base image, but that doesn't work out well either, because it means that upon updating, EVERYTHING gets reinstalled :/. Docker is supposed to be lighter weight than using VMs, but in this case it seems to me that it is indeed heavier, because the images are kind of forced to be monolithic due to the linear structure of the layer system, and yet they are immutable as well. This means that updates end up almost necessarilly being a very "heavy" operation. However, I have come up with a bit of a work-around. To emulate mutability by creating a "thin" layer at the "top" of each image into which updates can be installed.

![layout](https://cloud.githubusercontent.com/assets/1391608/16533821/bf11f1d0-3fdb-11e6-8d76-f200946f815c.png)

I don't really like this solution. But it should work, and it is currently feasable to implement, where-as re-designing Docker will have to wait a few more months at the very least.

**Comment by timthelion** [comment]
I'm closing this for now, because I think that the current situation should be much more satisfactory than when this was opened.
