### ISSUE TITLE
passthrough device

### ISSUE THREAD

**Issue by cinterloper** [subuser-security/subuser#299]
Is there an option to pass through a /dev device such as a webcam?

**Comment by timthelion** [comment]
The best option would be to run:

subuser subuser edit-permissions <subuser-name>

and add a "webcam 
<http://subuser.org/subuser-standard/permissions-dot-json-file-format.html>" 
property to the json object in permissions.json.

If that doesn't work, and you have the time, you could fix the code here 
<https://github.com/subuser-security/subuser/blob/master/logic/subuserlib/classes/subuserSubmodules/run/runtime.py#L122> 
and send me a pull request.

If your webcam is somehow weird and shouldn't be included in the 
standard webcam permission, or you only wrote "webcam" as an example and 
you really need some other device, then you could add a new permission 
<http://subuser.org/developers/common-tasks.html#adding-a-new-permission> 
for the device that you have in mind and send a pull request.

If your device is really essoteric and doesn't deserve its own 
permission, with the maintenance overhead of a special code path, you 
could add a "extra-devices" permission and send a pull request.

And if none of the above seems reasonable due to time constraints or 
some other reason, there is a sneeky environment variable that you can 
set which will set Docker run flags: http://subuser.org/commands/run.html

**Comment by cinterloper** [comment]
Thanks for the detailed reply.
I had been looking for the option on subuser.org but could not find it. 

I am interested in using cuda from within a container, passing through UVC webcams, and arbitrary input devices. 
this information helps alot.
