### ISSUE TITLE
How to make subuser to support "docker-ce"?

### ISSUE THREAD

**Issue by diyism** [subuser-security/subuser#347]
How to make subuser to support "docker-ce"? because docker-io is so stone-age.

**Comment by timthelion** [comment]
How does docker-ce differ in usage? What is broken?

**Comment by diyism** [comment]
Because that docker-io won't be support by most latest linux system, it will prevent users to intsall subuser successfully. For example, i'm using kali os or ubuntu os, after i downloaded subuser deb package from https://packages.debian.org/sid/all/subuser/download, and exec "gdebi subuser_0.6.2-3_all.deb", it will say: "This package is uninstallable Cannot install 'docker.io'"

**Comment by richard-delorenzi** [comment]
@diyism you should use `apt install`

@timthelion  I think that @diyism's problem is with debian deb packages. `subuser` requires `docker.io`

It could probably be fixed by Debian (and docker the provider of `docker-ce`), by having package `docker-ce`, and `docker.io` provide `docker-containers`, and `subuser` require `docker-containers`

**Comment by dragon788** [comment]
You can have a flexible requirement of `docker-ce || docker.io` in the Debian control files I think, no need to mess with a 3rd virtual package just to satisfy the need for a `docker` binary the user can use.

**Comment by diyism** [comment]
> You can have a flexible requirement of `docker-ce || docker.io` in the Debian control files I think, no need to mess with a 3rd virtual package just to satisfy the need for a `docker` binary the user can use.

Yes, we can re-package subuser: https://unix.stackexchange.com/a/534868/34654
